_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/model_reset_surgery.pth"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
    WITHECEA: True
    FREEZE_ECEA: True

  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 80
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
DATASETS:
  TRAIN: ('coco14_trainval_all','coco14_test_all',)
  TEST: ('coco14_test_all',)
SOLVER:
  IMS_PER_BATCH: 10
  BASE_LR: 0.01
  STEPS: (9600,)
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
  EVAL_PERIOD: 500
OUTPUT_DIR: "checkpoints/coco/stastic/"