_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "coco/model_reset_surgery.pth"
  MASK_ON: False
  BACKBONE:
    FREEZE: True
    WITHECEA: True
    FREEZE_ECEA: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 80
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
DATASETS:
  TRAIN: ('coco14_trainval_all_1shot_seed1',)
  TEST: ('coco14_test_all',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.02
  STEPS: (300, 800)
  MAX_ITER: 2000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 20
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
  EVAL_PERIOD: 500

OUTPUT_DIR: "checkpoints/1shot"