_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "voc/model_reset_surgery.pth"
  MASK_ON: False
  BACKBONE:
    FREEZE: True
    WITHECEA: True
    FREEZE_ECEA: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.001
    NUM_CLASSES: 20
    FREEZE_FEAT: True
    CLS_DROPOUT: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("voc_2007_trainval_all1_5shot_seed1", )
  TEST: ("voc_2007_test_all1",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (800, 1300)
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 0
  
  
TEST:
  EVAL_PERIOD: 500
  PCB_ENABLE: True
  PCB_MODELPATH: "ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
OUTPUT_DIR: "/Path/to/Output/Dir"